name: Test Backend

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run backend tests
        working-directory: apps/backend
        env:
          HTTP_PORT: 3000
          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          DATABASE_NAME: zakra
          DATABASE_PORT: 5432
          DATABASE_USER: ${{secrets.DATABASE_USER}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
        run: pnpm ci:test
